# Generated by Django 5.1.2 on 2024-10-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_masseurpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='masseurpage',
            name='membership_date',
            field=models.DateField(default=None, help_text='Membership date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='masseurpage',
            name='user_name',
            field=models.CharField(default=None, help_text='Name of the profile owner', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='masseurpage',
            name='user_profile_url',
            field=models.URLField(blank=True, help_text='URL to view all listings by the user'),
        ),
    ]
