# Generated by Django 5.1.2 on 2024-10-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_masseurindexpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masseurpage',
            options={'verbose_name': 'Masseur Page', 'verbose_name_plural': 'Masseur Pages'},
        ),
        migrations.AddField(
            model_name='masseurpage',
            name='location',
            field=models.CharField(blank=True, help_text='Location of the masseur', max_length=255),
        ),
    ]
